### ISSUE TITLE
thread 'main' panicked at 'already borrowed: BorrowMutError'

### ISSUE THREAD

**Issue by sitestudio** [Ivan-Velickovic/sel4cp_vmm#7]
Trying to run the following:

make BUILD_DIR=build \
SEL4CP_SDK=/home/andymc/Projects/seL4/CorePlatform/Velickovic/sel4cp/release/sel4cp-sdk-1.2.6 \
CONFIG=debug \
BOARD=qemu_arm_virt_hyp \
SYSTEM=simple.system \
run

but seeing this:

/home/andymc/Projects/seL4/CorePlatform/Velickovic/sel4cp/release/sel4cp-sdk-1.2.6/bin/sel4cp board/qemu_arm_virt_hyp/systems/simple.system --search-path build board/qemu_arm_virt_hyp/images --board qemu_arm_virt_hyp --config debug -o build/loader.img -r build/report.txt
thread 'main' panicked at 'already borrowed: BorrowMutError', /home/andymc/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.17.3/src/gil.rs:433:45
stack backtrace:
   0:     0x7f5ae36d67b0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::had334ddb529a2169
   1:     0x7f5ae3762c5e - core::fmt::write::h1aa7694f03e44db2
   2:     0x7f5ae36c80f5 - <unknown>
   3:     0x7f5ae36d6575 - <unknown>
   4:     0x7f5ae36d937f - <unknown>
   5:     0x7f5ae36d90ba - std::panicking::default_hook::he03a933a0f01790f
   6:     0x7f5ae36d9b28 - std::panicking::rust_panic_with_hook::he26b680bfd953008
   7:     0x7f5ae36d98c7 - <unknown>
   8:     0x7f5ae36d6c5c - <unknown>
   9:     0x7f5ae36d95e2 - rust_begin_unwind
  10:     0x7f5ae28920d3 - core::panicking::panic_fmt::he7679b415d25c5f4
  11:     0x7f5ae2892393 - core::result::unwrap_failed::hb71caff146724b6b
  12:     0x7f5ae2b42086 - pyo3::gil::register_owned::h998547cdd21fc09e
  13:     0x7f5ae2b548c8 - pyo3::types::string::PyString::new::heccde79697d72abe
  14:     0x7f5ae2894e4d - <unknown>
  15:     0x7f5ae2896aa4 - pyembed::interpreter::MainPythonInterpreter::new::h6ff8b944283a0e80
  16:     0x7f5ae2893345 - <unknown>
  17:     0x7f5ae2893663 - <unknown>
  18:     0x7f5ae28927d9 - <unknown>
  19:     0x7f5ae36b91ee - std::rt::lang_start_internal::h167a33dedfef305a
  20:     0x7f5ae2893655 - main
make: *** [Makefile:137: build/loader.img] Error 101

**Comment by Ivan-Velickovic** [comment]
Hi, what operating system is this on? If macOS, what version of macOS and what architecture (x86 or ARM)?

I haven't seen an error like this before. Would you be able to try using an SDK from here: https://github.com/Ivan-Velickovic/sel4cp/actions/runs/5340642791?

**Comment by sitestudio** [comment]
Hi Ivan,

Thanks for the link to the workshop CI artefacts.

it's on x64 Ubuntu 22.04.

I see your ci.yml is 20.04 - in a couple of days I will try to replicate that Ubuntu 20.04 setup as a VM locally here.

Also, I was able to get https://github.com/perpen/sel4cp-container to work - although I had to use "FROM Ubuntu:20.04".

Also tried on an 18.04 VM last night (following the README.md links on this repo as closely as possible) but got the following error:

python3.9 build_sdk.py --sel4=/home/andymc/projects/velickovic/seL4
Building seL4: sel4_dir=PosixPath('/home/andymc/projects/velickovic/seL4') root_dir=PosixPath('release/sel4cp-sdk-1.2.6') build_dir=PosixPath('build/tqma8xqp1gb/release/sel4') board=BoardInfo(name='tqma8xqp1gb', arch=1, gcc_flags='GCC_CPU=cortex-a35', loader_link_address=2150105088, kernel_options={'KernelPlatform': 'tqma8xqp1gb', 'KernelIsMCS': True, 'KernelArmExportPCNTUser': True}, examples={'ethernet': PosixPath('example/tqma8xqp1gb/ethernet')}) config=ConfigInfo(name='release', debug=False, kernel_options={})
CMake Error: The source directory "/home/andymc/projects/velickovic/sel4cp/build/tqma8xqp1gb/release/sel4/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Traceback (most recent call last):
  File "/home/andymc/projects/velickovic/sel4cp/build_sdk.py", line 896, in <module>
    main()
  File "/home/andymc/projects/velickovic/sel4cp/build_sdk.py", line 843, in main
    build_sel4(sel4_dir, root_dir, build_dir, board, config)
  File "/home/andymc/projects/velickovic/sel4cp/build_sdk.py", line 604, in build_sel4
    raise Exception(f"Error configuring sel4: cmd={cmd}")
Exception: Error configuring sel4: cmd=cmake -GNinja -DCMAKE_INSTALL_PREFIX=/home/andymc/projects/velickovic/sel4cp/build/tqma8xqp1gb/release/sel4/install  -DPYTHON3=/usr/local/bin/python3.9  -DKernelArmExportPCNTUser=ON -DKernelIsMCS=ON -DKernelPlatform=tqma8xqp1gb -S /home/andymc/projects/velickovic/seL4 -B /home/andymc/projects/velickovic/sel4cp/build/tqma8xqp1gb/release/sel4/build

Anyhow, the path forward seems to be to look into ci.yml and either set it up as a VM or use the Docker container as described.

Thanks for the help.

Andrew

**Comment by sitestudio** [comment]
Tried with the ci build and it works great. Thanks Ivan.

**Comment by Ivan-Velickovic** [comment]
> Tried with the ci build and it works great. Thanks Ivan.

Ah good. Just to clarify that it's the `dev` branch ones you want rather than the workshop ones. How did you setup your Ubuntu 22.04 environment? I've had it working in the past although haven't tried it in a while. Please feel free to report any issues since internally the SDK has been fairly stable but I don't know if others have run into weird issues like this.

**Comment by sitestudio** [comment]
Yes, followed the link from this repo to your dev branch of sel4cp (https://github.com/Ivan-Velickovic/sel4cp/tree/dev).

Ah, I didn't have the right SDK setup on it. That makes sense as causing that error.

Will try another Ubuntu 22.04 machine in the next few days and confirm.

**Comment by sitestudio** [comment]
All working now on ubuntu 22.04. My bad, didn't follow the bits about the specific ARM and RISCV toolchains.
