### ISSUE TITLE
implicit-function-declaration error running make for zcu102

### ISSUE THREAD

**Issue by sitestudio** [Ivan-Velickovic/sel4cp_vmm#9]
Trying to build for zcu102 (on zcu102_support branch) but seeing the following:

```
aarch64-linux-gnu-gcc -c -mstrict-align -nostdlib -ffreestanding -g3 -O3 -Wall -Wno-unused-function -Werror -I/home/andymc/Projects/seL4/Velickovic/sel4cp/release/sel4cp-sdk-1.2.6/board/zcu102/debug/include -DBOARD_zcu102 -DCONFIG_debug src/vmm.c -o build/vmm.o
In file included from src/vmm.c:9:
src/util/util.h: In function ‘print_vcpu_regs’:
src/util/util.h:125:34: error: implicit declaration of function ‘sel4cp_arm_vcpu_read_reg’ [-Werror=implicit-function-declaration]
  125 |     printf("    SCTLR: 0x%lx\n", sel4cp_arm_vcpu_read_reg(vcpu_id, seL4_VCPUReg_SCTLR));
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~
src/util/util.h:125:68: error: ‘seL4_VCPUReg_SCTLR’ undeclared (first use in this function)
  125 |     printf("    SCTLR: 0x%lx\n", sel4cp_arm_vcpu_read_reg(vcpu_id, seL4_VCPUReg_SCTLR));
```

Am able to successfully run make for rpi4b_hyp for example using

```
make BUILD_DIR=build \
SEL4CP_SDK=/home/andymc/Projects/seL4/Velickovic/sel4cp/release/sel4cp-sdk-1.2.6 \
CONFIG=debug \
BOARD=rpi4b_hyp \
SYSTEM=simple.system \
```

Same result on a couple of different boxes.

Verified that constants.h has the required enums in release/sel4cp-sdk-1.2.6/board/zcu102/debug/include/sel4/sel4_arch directory.

**Comment by Ivan-Velickovic** [comment]
My bad, I forgot to push the change to seL4CP that builds the kernel for the ZCU102 with hypervisor support (these libsel4cp functions only exist when the kernel has hypervisor mode enabled). You can either pull the changes and rebuild the SDK or download the SDK from here https://github.com/Ivan-Velickovic/sel4cp/actions/runs/5451724984.

**Comment by sitestudio** [comment]
Thank you for pushing the changes. All builds now.
